version: '3.8'

services:
  app:
    image: "221082200491.dkr.ecr.ap-northeast-2.amazonaws.com/todorian:todorian"
    ports:
      - "80:8080"
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
