services:
  app:
    image: "221082200491.dkr.ecr.ap-northeast-2.amazonaws.com/todorian:todorian"
    ports:
      - "80:8080"
    environment:
      - SPRING_REDIS_HOST=aws_beanstalk/current-app
      - SPRING_REDIS_PORT=${secrets.SPRING_REDIS_PORT}
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: aws_beanstalk/current-app
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge