spring:
  datasource:
    driver-class-name:
    url:
    username:
    password:

  application:
    name: todorian

  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${ secrets.JWT_SECRET }

logging:
  level:
    '[com.todorian]': debug
    '[org.hibernate.type]': trace