server:
  tomcat:
    mbeanregistry:
      enabled: true

  port: ${SERVER.PORT}

spring:
  profiles:
    active:
      - local
  application:
    name: todorian
  config:
    import: optional:file:.env[.properties]

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

management:
  endpoints:
    web:
      base-path: /api/actuator
      exposure:
        include: "prometheus"

#discord
#  environment: prod
#  webhook-url: https://discord.com/api/webhooks/1298910673836703795/VoW2yqBbI_DZQ-3tUVgAzLfnhyqmU5RIO5vu6hUMCwvAzSuHUJ920zpX0hm5JnZ-cUSj

logging:
  level:
    io.netty: DEBUG