spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${secrets.SPRING_DATASOURCE_URL}
    username: ${secrets.SPRING_DATASOURCE_USERNAME}
    password: ${secrets.SPRING_DATASOURCE_PASSWORD}
  application:
    name: todorian

  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: ${secrets.SPRING_REDIS_HOST}
      port: ${secrets.SPRING_REDIS_PORT}

jwt:
  secret: ${ secrets.JWT_SECRET }

logging:
  level:
    '[com.todorian]': debug
    '[org.hibernate.type]': trace

server:
  port: 8080