spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://awseb-e-6c2imjc3bx-stack-awsebrdsdatabase-05ajrgl8weim.cpiycgkkk147.ap-northeast-2.rds.amazonaws.com:3306/TODORIAN
    username: todorian
    password: todorian

  h2:
    console:
      enabled: true

  application:
    name: ticketaka

  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

jwt:
  secret: ${JWT.SECRET}